### LOGIN ADMIN
POST http://127.0.0.1:8000/auth/login/
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###
### POST Create Event (ADMIN)
POST http://127.0.0.1:8000/events/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc1NjAyOTYwLCJpYXQiOjE3NzU2MDI2NjAsImp0aSI6IjM3NzczODVlZTVhMzRkMDdhNmM5YjkyNjFhNDM1OWYwIiwidXNlcl9pZCI6IjEiLCJyb2xlIjoidmlld2VyIn0.nnaHhqp87m21O6V9fz_RgQIbgs29u-oF9bvktpDahjA
Content-Type: application/json

{
  "title": "Hackathon AI",
  "description": "Événement sur l'IA",
  "date": "2026-05-01",
  "location": "Paris",
  "status": "upcoming"
}