
### Get all events
GET http://127.0.0.1:8000/events/

###

### Create event
POST http://127.0.0.1:8000/events/
Content-Type: application/json

{
  "title": "AI Conference",
  "description": "Conference about Artificial Intelligence",
  "date": "2026-07-10",
  "location": "Paris",
  "status": "upcoming"
}

###
